### ISSUE TITLE
error: failed to run custom build command for `mupdf-sys v0.0.3`

### ISSUE THREAD

**Issue by 1138886114** [messense/mupdf-rs#15]
[dependencies]
mupdf = "0.0.3"

Compilation error：
error: failed to run custom build command for `mupdf-sys v0.0.3`  

Whether mupdf needs to be installed first, how to install it

**Comment by messense** [comment]
Please provide full error message.

**Comment by 1138886114** [comment]
D:\Rust\projects\mupdf_001>cargo build -vv
       Fresh unicode-xid v0.2.1
       Fresh glob v0.3.0
       Fresh cc v1.0.62
       Fresh version_check v0.1.5
       Fresh lazy_static v1.4.0
       Fresh quick-error v1.2.3
       Fresh cfg-if v0.1.10
       Fresh unicode-width v0.1.8
       Fresh regex-syntax v0.6.21
       Fresh strsim v0.8.0
       Fresh vec_map v0.8.2
       Fresh rustc-hash v1.1.0
       Fresh peeking_take_while v0.1.2
       Fresh shlex v0.1.1
       Fresh lazycell v1.3.0
       Fresh once_cell v1.5.0
       Fresh thread_local v1.0.1
       Fresh humantime v1.3.0
       Fresh textwrap v0.11.0
       Fresh winapi v0.3.9
       Fresh proc-macro2 v1.0.24
       Fresh memchr v2.3.4
       Fresh libc v0.2.80
       Fresh log v0.4.11
       Fresh bitflags v1.2.1
       Fresh serde v1.0.117
       Fresh quote v1.0.7
       Fresh atty v0.2.14
       Fresh aho-corasick v0.7.15
       Fresh winapi-util v0.1.5
       Fresh nom v4.2.3
       Fresh libloading v0.5.2
       Fresh which v3.1.1
       Fresh regex v1.4.2
       Fresh termcolor v1.1.0
       Fresh clap v2.33.3
       Fresh syn v1.0.48
       Fresh toml v0.5.7
       Fresh clang-sys v0.28.1
       Fresh cexpr v0.3.6
       Fresh env_logger v0.7.1
       Fresh proc-macro-crate v0.1.5
       Fresh derivative v2.1.1
       Fresh bindgen v0.52.0
       Fresh num_enum_derive v0.4.3
       Fresh num_enum v0.4.3
   Compiling mupdf-sys v0.0.3
     Running `D:\Rust\projects\mupdf_001\target\debug\build\mupdf-sys-e4712e518f26b41c\build-script-build`
[mupdf-sys 0.0.3] cargo:rerun-if-changed=wrapper.h
[mupdf-sys 0.0.3] cargo:rerun-if-changed=wrapper.c
[mupdf-sys 0.0.3] thread 'main' panicked at 'make failed: Os { code: 2, kind: NotFound, message: "The system could not find the specified file." }', C:\Users\xxxx\.cargo\registry
\src\mirrors.ustc.edu.cn-61ef6e0cd06fb9b8\mupdf-sys-0.0.3\build.rs:43:10
[mupdf-sys 0.0.3] note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: failed to run custom build command for `mupdf-sys v0.0.3`

Caused by:
  process didn't exit successfully: `D:\Rust\projects\mupdf_001\target\debug\build\mupdf-sys-e4712e518f26b41c\build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-changed=wrapper.h
  cargo:rerun-if-changed=wrapper.c

  --- stderr
  thread 'main' panicked at 'make failed: Os { code: 2, kind: NotFound, message: "The system could not find the specified file." }', C:\Users\xxxx\.cargo\registry\src\mirrors.ust
c.edu.cn-61ef6e0cd06fb9b8\mupdf-sys-0.0.3\build.rs:43:10
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by 1138886114** [comment]
D:\Rust\projects\mupdf_001>cargo build -vv
   Compiling winapi v0.3.9
   Compiling memchr v2.3.4
   Compiling proc-macro2 v1.0.24
   Compiling unicode-xid v0.2.1
   Compiling libc v0.2.80
   Compiling glob v0.3.0
   Compiling cc v1.0.62
   Compiling version_check v0.1.5
   Compiling log v0.4.11
   Compiling lazy_static v1.4.0
   Compiling bitflags v1.2.1
   Compiling unicode-width v0.1.8
   Compiling regex-syntax v0.6.21
   Compiling cfg-if v0.1.10
   Compiling quick-error v1.2.3
   Compiling serde v1.0.117
   Compiling strsim v0.8.0
   Compiling bindgen v0.52.0
   Compiling syn v1.0.48
   Compiling vec_map v0.8.2
   Compiling peeking_take_while v0.1.2
   Compiling lazycell v1.3.0
   Compiling shlex v0.1.1
   Compiling rustc-hash v1.1.0
   Compiling once_cell v1.5.0
   Compiling nom v4.2.3
   Compiling thread_local v1.0.1
   Compiling textwrap v0.11.0
   Compiling humantime v1.3.0
   Compiling clang-sys v0.28.1
   Compiling which v3.1.1
   Compiling aho-corasick v0.7.15
   Compiling quote v1.0.7
   Compiling libloading v0.5.2
   Compiling regex v1.4.2
   Compiling cexpr v0.3.6
   Compiling winapi-util v0.1.5
   Compiling atty v0.2.14
   Compiling termcolor v1.1.0
   Compiling clap v2.33.3
   Compiling env_logger v0.7.1
   Compiling derivative v2.1.1
   Compiling toml v0.5.7
   Compiling proc-macro-crate v0.1.5
   Compiling num_enum_derive v0.4.3
   Compiling num_enum v0.4.3
   Compiling mupdf-sys v0.0.3
     Running `D:\Rust\projects\mupdf_001\target\debug\build\mupdf-sys-e4712e518f26b41c\build-script-build`
[mupdf-sys 0.0.3] cargo:rerun-if-changed=wrapper.h
[mupdf-sys 0.0.3] cargo:rerun-if-changed=wrapper.c
[mupdf-sys 0.0.3] thread 'main' panicked at 'make failed: Os { code: 2, kind: NotFound, message: "The system could not find the specified file." }', C:\Users\xxxx\.cargo\registry
\src\mirrors.ustc.edu.cn-61ef6e0cd06fb9b8\mupdf-sys-0.0.3\build.rs:43:10
[mupdf-sys 0.0.3] note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: failed to run custom build command for `mupdf-sys v0.0.3`

Caused by:
  process didn't exit successfully: `D:\Rust\projects\mupdf_001\target\debug\build\mupdf-sys-e4712e518f26b41c\build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-changed=wrapper.h
  cargo:rerun-if-changed=wrapper.c

  --- stderr
  thread 'main' panicked at 'make failed: Os { code: 2, kind: NotFound, message: "The system could not find the specified file." }', C:\Users\xxxx\.cargo\registry\src\mirrors.ust
c.edu.cn-61ef6e0cd06fb9b8\mupdf-sys-0.0.3\build.rs:43:10
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


The above information is the compilation error details！

**Comment by messense** [comment]
You are using Windows, right? I did not test on Windows, will do later.

**Comment by dyaso** [comment]
I had the same problem, using Windows 10.
Noticing that line 43 of `mupdf-sys-0.0.3\build.rs` invokes the GNU `make` utility, i installed that via the [Chocolatey](https://chocolatey.org/install) package manager; now the error is
```
PS C:\Users\user\Documents\GitHub\ebook-juggler\ebook-juggler> cargo build
   Compiling mupdf-sys v0.0.3
error: failed to run custom build command for `mupdf-sys v0.0.3`

Caused by:
  process didn't exit successfully: `C:\Users\user\Documents\GitHub\ebook-juggler\ebook-juggler\target\debug\build\mupdf-sys-cb0d3627e8183403\build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-changed=wrapper.h
  cargo:rerun-if-changed=wrapper.c
  mkdir -p C:\Users\user\Documents\GitHub\ebook-juggler\ebook-juggler\target\debug\build\mupdf-sys-4950eff510008997\out/source/fitz/ ; cc -ffunction-sections -fdata-sections -pipe -g -DNOTO_SMALL -DNO_CJK -Iinclude -MMD -MP -o C:\Users\user\Documents\GitHub\ebook-juggler\ebook-juggler\target\debug\build\mupdf-sys-4950eff510008997\out/source/fitz/archive.o -c source/fitz/archive.c -Wall -Wdeclaration-after-statement -Iscripts/freetype -Ithirdparty/freetype/include -Ithirdparty/harfbuzz/src -Iscripts/libjpeg -Ithirdparty/libjpeg -Ithirdparty/lcms2/include -DHAVE_LCMS2MT -Ithirdparty/mujs -Ithirdparty/zlib -Ithirdparty/jbig2dec -Ithirdparty/openjpeg/src/lib/openjp2 -DOPJ_STATIC -DOPJ_HAVE_STDINT_H -DOPJ_HAVE_INTTYPES_H -DMUTEX_pthread=0

  --- stderr
  process_begin: CreateProcess(NULL, uname, ...) failed.
  Makerules:3: pipe: No error
  File not found - *.[ch]
  The syntax of the command is incorrect.
  make: *** [Makefile:101: C:\Users\user\Documents\GitHub\ebook-juggler\ebook-juggler\target\debug\build\mupdf-sys-4950eff510008997\out/source/fitz/archive.o] Error 1
  thread 'main' panicked at '""', C:\Users\user\.cargo\registry\src\github.com-1ecc6299db9ec823\mupdf-sys-0.0.3\build.rs:45:9
```
MuPDF can definitely be compiled for Windows as they offer [pre-built binaries on their site](https://mupdf.com/downloads/index.html) (although only as apps, not libraries for linking to, unfortunately).

**Comment by dyaso** [comment]
The SumatraPDF reader also builds a Windows copy of mupdf, apparently using some Lua based build system https://github.com/sumatrapdfreader/sumatrapdf

**Comment by dyaso** [comment]
Got it to build and the `mupdf-rs` tests to pass by doing the following:

- use Visual Studio to compile `mupdf-sys/mupdf/platform/win32/mupdf.sln` in 64-bit mode
- comment out lines [82-96 of `mupdf-sys/build.rs`](https://github.com/messense/mupdf-rs/blob/8a3abc0228c92dc6b437d6bfac2365df4a5a2ffa/mupdf-sys/build.rs#L82)
- replace them with:
```rust
    let mut mupdf_dir_string = String::new();
    for mut it in mupdf_dir.iter() {
        let component = it.to_str().unwrap();
        if component != "\\" {
            mupdf_dir_string += component;
            mupdf_dir_string += "/";
        }
    }

    println!("cargo:rustc-link-search=native={}platform/win32/x64/Debug/", mupdf_dir_string);
    println!("cargo:rustc-link-lib=dylib=libmupdf");
    println!("cargo:rustc-link-lib=dylib=libthirdparty");
```
note that the libraries are being linked as 'dylib', not 'static'. People on the Rust Programming Language Community discord channel `#windows-dev` suggested that, and it was the only way I could get it to work -- Rust's linking model is apparently at odds with how Windows does things.

**Comment by messense** [comment]
@dyaso If you can figure out how to compile `mupdf-sys/mupdf/platform/win32/mupdf.sln` in command line instead of Visual Studio IDE, we can integrate the build process in `build.rs` for automation.
