### ISSUE TITLE
centos build project mupdf error

### ISSUE THREAD

**Issue by 1138886114** [messense/mupdf-rs#19]
thread 'main' panicked at 'Unable to find libclang: "couldn\'t find any valid shared libraries matching: [\'libclang.so\', \'libclang-*.so\', \'libclang.so.*\', \'libclang-*.so.*\'], set the `LIBCLANG_PATH` environment variable to a path where one of these files can be found (invalid: [])"', /root/.cargo/registry/src/crates.rustcc.com-a21e0f92747beca3/bindgen-0.56.0/src/lib.rs:1922:31

**Comment by messense** [comment]
https://rust-lang.github.io/rust-bindgen/requirements.html

You need to install clang/llvm.
