### ISSUE TITLE
Render pdf as HTML

### ISSUE THREAD

**Issue by genderev** [messense/mupdf-rs#21]
I saw the [test](https://github.com/messense/mupdf-rs/blob/master/tests/test_issue_16.rs) which renders a PDF as a PNG. Is it possible to render a PDF as HTML with mupdf-rs? I really like this project. I was unable to find this in the [documentation](https://docs.rs/mupdf/0.1.1/mupdf/).

**Comment by genderev** [comment]
Actually, I found this [function](https://docs.rs/mupdf/0.1.1/src/mupdf/page.rs.html#224-232), I think I'll figure it out.

**Comment by messense** [comment]
https://github.com/messense/mupdf-rs/blob/8a3abc0228c92dc6b437d6bfac2365df4a5a2ffa/src/page.rs#L366-L380

**Comment by genderev** [comment]
Thanks! I was able to try it out.
