### ISSUE TITLE
Flatten causes STATUS_ACCESS_VIOLATION

### ISSUE THREAD

**Issue by GeorgOhneH** [messense/mupdf-rs#27]
OS: Windows 10 64bit
mupdf-rs version: current github version (build from source)

This code: 

```
let doc = PdfDocument::open("filename.pdf")?;
    doc.pages()?
        .map(|page| Ok(page?.to_text_page(TextPageOptions::PRESERVE_LIGATURES)?))
        .collect::<Result<Vec<_>, Error>>()?
        .into_iter()
        .map(|text_page| text_page.blocks())
        .flatten()
        .collect::<Vec<_>>();
```

produces this error:
`error: process didn't exit successfully: ... (exit code: 0xc0000005, STATUS_ACCESS_VIOLATION)`

Also, when you remove the `flatten`, it works again

**Comment by messense** [comment]
Wasn't able to reproduce this issue with current master branch in https://github.com/messense/mupdf-rs/pull/33 , feel free to reopen if it still fails.
