### ISSUE TITLE
Configurable MuPDF features

### ISSUE THREAD

**Issue by messense** [messense/mupdf-rs#4]
- [ ] X11 support
- [ ] GL support
- [ ] Use system libraries
- [ ] Embed font

https://github.com/messense/mupdf-rs/blob/76fe49fe119f126aff28c2c789a9190f7df36e67/mupdf-sys/build.rs#L33-L38

**Comment by messense** [comment]
Note that adding more fonts will increase the size of `mupdf-sys` crate, and if the size if over 10MB, it can't be released on `crates.io`

**Comment by messense** [comment]
@NBonaparte Would you like to tackle this one?

**Comment by NBonaparte** [comment]
Sure, is it just turning the first four flags into features?

**Comment by messense** [comment]
I think so. https://github.com/messense/mupdf-rs/blob/master/mupdf-sys/Cargo.toml#L6-L30 also needs some tweaks.
