### ISSUE TITLE
Is there a way to replace the outline of pdf ?

### ISSUE THREAD

**Issue by TD-Sky** [messense/mupdf-rs#54]
I have seek the whole document and didn't find any methods to do that.

It is similar to the method [fitz.Document.set_toc](https://pymupdf.readthedocs.io/en/latest/document.html#Document.set_toc) in pymupdf.

Is it an oversight on my part? Or is this feature not yet developed ?

**Comment by messense** [comment]
> I have seek the whole document and didn't find any methods to do that.

That's obviously not implemented yet. Pull requests are welcome.
