### ISSUE TITLE
Segmentation fault at page.to_display_list()

### ISSUE THREAD

**Issue by c4ys** [messense/mupdf-rs#60]
mupdf相对pdfium以及xpdf一个优势是对多核渲染的支持,
在实际使用mupdf-rs过程中发现部分文件 page.to_display_list()发生Segmentation fault且没有提示,
使用官方mupdf和C++编译的mutool则不会发生错误.

**Comment by messense** [comment]
Please provide a minimal reproduction code.

**Comment by c4ys** [comment]
上次是用mutool,
今天试了下用官方多线程也成功了.

https://github.com/ArtifexSoftware/mupdf/blob/master/docs/examples/multi-threaded.c


接下来我有空将mupdf-rs改写下看是否能成功.

**Comment by messense** [comment]
Fixed in #61
