### ISSUE TITLE
Segmentation fault in image_filter_callback/set_image_filter

### ISSUE THREAD

**Issue by Shadow53** [messense/mupdf-rs#62]
When I process images using `set_image_filter`, I get a segmentation fault.

I was able to trace the issue to [this line](https://github.com/messense/mupdf-rs/blob/77f17e2b52beeeb108927f65471f122dc572740e/src/pdf/filter.rs#L127), where `ret.inner` is copied (since pointers are `Copy`) and returned, and `ret` is dropped, which frees the memory using mupdf's [`fz_drop_image`](https://github.com/messense/mupdf-rs/blob/77f17e2b52beeeb108927f65471f122dc572740e/src/image.rs#L109).

**Comment by Shadow53** [comment]
The immediate solution I see is to swap `ret.inner` with a `nullptr` and return the swapped-out value, but I am wondering if you would be open to a PR with a larger refactor that wraps pointers in `Rc`/`Arc` internally to avoid this sort of problem in the future.

**Comment by messense** [comment]
Sure! Pull requests are welcome.

**Comment by Shadow53** [comment]
Worked at this for a bit, only to realize that `fz_keep_*` and `fz_drop_*` increase/decrease existing reference counts, so adding Rust-level reference counting would be unnecessary complexity on top of that.

About to open a PR that just fixes this issue instead of refactoring everything.
